name: Nx Deploy
on: [push, pull_request]
env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: config private registry
        run: npm config set '@paladin-analytics:registry' "https://npm.pkg.github.com"
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      # caching deps
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install
      - name: building app and lib
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy-app:
    # DEPLOY THE APP TO FIREBASE
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: ls
        run: ls
  publish-pkg:
    # deploy package to github packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: add publish config to npm
        working-directory: ./libs/react-pdf-components
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
          npm publish --no-git-tag-version --no-push --yes --dry-run
