name: deploy app for preview
on:
  pull_request:
    branches:
      - main
env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  deploy-app-preview:
    runs-on: ubuntu-latest
    env:
      deployChannel: rpc-${{ github.event.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.0

      - name: config private registry
        run: npm config set '@paladin-analytics:registry' "https://npm.pkg.github.com"
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      # caching deps

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install firebase
        run: npm i firebase-tools -g

      - name: install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install

      - name: building app and lib
        run: npm run build app

      - name: deploy for preview
        run: npm run firebase:deploy:preview -- "$deployChannel" -P default --token $FIREBASE_TOKEN

      - name: set deploy URL
        run: echo "DURL=$(firebase hosting:channel:open $deployChannel)" >> $GITHUB_ENV

      - name: Comment preview URL on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Deployed to preview channel > [${{ env.DURL }}](${{ env.DURL }})
          comment_includes: 'Deployed'
          reactions: hooray
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
